CREATE TABLE IF NOT EXISTS USERS (
      ID INT NOT NULL,
      BRAND_ID INT NOT NULL,
      START_DATE TIMESTAMP NOT NULL,
      END_DATE TIMESTAMP  NOT NULL,
      PRICE_LIST INT NOT NULL,
      PRODUCT_ID INT NOT NULL,
      PRIORITY INT NOT NULL,
      PRICE DOUBLE NOT NULL,
      CURR VARCHAR (5) NOT NULL,
      PRIMARY KEY (ID)
);